[package]
name = "serial-to-tcp"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "3.1", features = ["cargo"] }
lazy_static = "1.4"
log = "0.4"
simple_logger = "2.1"
tokio = { version = "1.17.0", features = ["full"] }
tokio-serial = "5.4"
