name: serial-to-tcp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Cache registry
      uses: actions/cache@v3.0.11
      with:
        path: ~/.cargo/registry
        key: "cargo-registry"
    - name: Cache build output
      uses: actions/cache@v3.0.11
      with:
        path: target
        key: "build-output"
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check
  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - name: Cache registry
      uses: actions/cache@v3.0.11
      with:
        path: ~/.cargo/registry
        key: "cargo-registry"
    - name: Cache build output
      uses: actions/cache@v3.0.11
      with:
        path: target
        key: "build-output"
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Cache registry
      uses: actions/cache@v3.0.11
      with:
        path: ~/.cargo/registry
        key: "cargo-registry"
    - name: Cache build output
      uses: actions/cache@v3.0.11
      with:
        path: target
        key: "build-output"
    - uses: actions/checkout@v3
    - name: Run unit tests
      run: cargo test
